### ISSUE TITLE
Provide affordance/clue for oscillator waveform options

### ISSUE THREAD

**Issue by philipbelesky** [AlasdairMott/Siren#4]
With components that hide state in the context menu I find it useful that there is some visual indicator of what the current value is. This also helps as a prompt to explore/check the context menu itself. In the demo file it took me a while to realise the wave form could change.

Options for consideration (I'd be happy to implement whatever you'd prefer):

- An icon that changes to reflect each waveform
- Create a 'normal' input for it and transfer the selection dropdown there (I think this is possible)
- A sub-panel readout with current oscillator type like:

<img width="521" alt="Screen Shot 2021-10-05 at 6 50 32 pm" src="https://user-images.githubusercontent.com/495961/135983315-e88e839e-055d-4890-97ad-1c65eaf2b43e.png">

- Add a dropdown as part of the component itself like:

<img width="355" alt="Screen Shot 2021-10-05 at 6 54 46 pm" src="https://user-images.githubusercontent.com/495961/135983025-e449d9fa-36d8-4664-b61c-27fe625c3a8e.png">

**Comment by AlasdairMott** [comment]
I think thats a really good idea.

> An icon that changes to reflect each waveform

It could be like the geometry pipeline menu - we could even stack waveforms if we allow multiple types to be selected.
![image](https://user-images.githubusercontent.com/25563790/136092908-5c8351e5-84ac-4f47-9ddb-39ead50df8ac.png)

> Create a 'normal' input for it and transfer the selection dropdown there (I think this is possible)

I like things to be a 'modular' as possible but I'm also a fan of less inputs, and 'set it and forget it' for one off values. 

All the approaches you mentioned look really good, I think its a matter of testing to see whats most comfortable to use.
