### ISSUE TITLE
Add sample wavs used in the second demo file

### ISSUE THREAD

**Issue by philipbelesky** [AlasdairMott/Siren#5]
It would be great to bundle the samples used in the second demo file as part of the repo (if they are public-domainable). I don't work with samples much so don't tend to have an organised/coherent set ready to slot in.

As there are a few files to wire up, it can be convenient to have the script reads files from the definition's folder rather than a user-specific path. I generally use a small python script for this that takes the filename as an input:

```
import os

script_path = ghenv.Component.OnPingDocument().FilePath
script_folder = os.path.dirname(script_path)
output_path = os.path.join(script_folder, file_name)
```

**Comment by AlasdairMott** [comment]
Attached some samples this morning. Used your python script to link them :)
