### ISSUE TITLE
Add playhead to waveform visualisations

### ISSUE THREAD

**Issue by philipbelesky** [AlasdairMott/Siren#9]
When playing longer sounds it can be useful to visually track the currently-playing sound against the waveform and adjacent input geometry. This is probably particularly useful with LFOs or evaluating the effects of the time parameters.

If desirable, my first thought for implementation would be to add an output for the sound player that could then be connected to the waveform visualiser, providing a simple "% played" number that could be used to render a moving line. This is a little inelegant as there's no guarantee the right connection was made.

There's probably a way to do it without an explicit parameter connection - e.g. some sort of asynchronous communication from the player component to visualisers that have matching inputs. But that's a weird Grasshopper behaviour and perhaps more trouble than its worth to implement.

**Comment by AlasdairMott** [comment]
I agree, some sort of feedback would help alot. I'm not sure what would happen to the % out if its constantly updating, will the downstream operations will keep up with the playhead? Might just need to experiment a bit. Asynchronous communication sounds like it will be tricky.

What about having a playhead on the playback component?

![playheads](https://user-images.githubusercontent.com/25563790/136512177-d5896f2c-cdc4-448a-adbc-457831517ad8.jpg)

**Comment by philipbelesky** [comment]
A playhead on the component would get most of the way to showing play position against the waveform, although it wouldn't really help with reading the play position vs the controlled geometry (given those are generally adjacent anyway). The size of the component might also be a bit limited for longer running samples as well.

I think downstream latency should be avoidable by having `SampleToPolylineComponent` make a crude hash of its inputs (except for `Play %`) and output a cached copy of the waveform curve unless they change. So, in theory the component should only need to update a line's position in response to `Play %` updates. I'll have a go at an implementation and see how it performs.
